# docker-compose.yml
version: '3.8'

services:
  # Java бэкенд
  backend:
    build:
      context: /path/to/your/java/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DB_URL=jdbc:postgresql://db:5432/yourdb
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - app-network

  # Next.js фронтенд
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network

  # База данных (если нужно)
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Nginx для проксирования
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge