spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dugaweldDB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1706}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
jwt:
  secret: ${JWT_SECRET:_;K{/8`Vz6dUskC|"v%0[eG\,pD9@>HZmqoJX+Mb}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

# MinIO Configuration
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:dugaweld-images}

# Legacy file storage (will be replaced by MinIO)
saveImagesPath: ${SAVE_IMAGES_PATH:/opt/dugaweld/images/}
getImagesPath: ${GET_IMAGES_PATH:http://141.105.71.70/images/}